language: cpp

matrix:
  include:
    - os: linux
      arch:
        - amd64
        - arm64
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - TYPE=Debug

    - os: linux
      arch:
        - amd64
        - arm64
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
         - TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Release

    - os: osx
      sudo: required
      env: 
        - TYPE=Debug
      
before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
  - python install.py -install


script:
  - while sleep 400; do echo "=====[ $SECONDS seconds ]====="; done &
  - cmake -DCMAKE_BUILD_TYPE=$TYPE -DENABLE_FLOAT=On .
  - make 
  - ./bin/prp
  - ./bin/prg
  - ./bin/mitccrh
  - ./run ./bin/garble
  - ./run ./bin/netio
  - ./bin/bit
  - ./bin/int
  - ./bin/float
  - ./bin/ecc
  - ./bin/f2k
